-- CRIAR E POPULAR A TABELA CLIENTES
CREATE TABLE clientes (
    id INTEGER NOT NULL GENERATED ALWAYS
        AS IDENTITY (START WITH 1, INCREMENT BY 1),
    nome VARCHAR(50),
    endereco VARCHAR(60),
    telefone VARCHAR(14),
    email VARCHAR(50)
);

-- CRIAR E POPULAR A TABELA PRODUTOS
CREATE TABLE produtos (
    id INTEGER NOT NULL GENERATED ALWAYS
        AS IDENTITY (START WITH 1, INCREMENT BY 1),
    descricao VARCHAR(50),
    custo DECIMAL(12,2),
    quantidade INTEGER
);
